### PR TITLE
Release 2.0.2

### PR DESCRIPTION
**Pull request by kemitchell**
PR to propose releasing v2.0.2, with the new handwritten parser.

If there is any reason to think the new implementation might return different results than the old, generated parser, we should bump SemVer major instead, and perhaps do a 3.0.0-pre.1.

### CODE REVIEW

**Comment by motet-a** [comment]
Since there were not many tests in `spdx-expression-parse` but other packages like `spdx-correct` or `validate-npm-package-license` contain [much](https://github.com/kemitchell/validate-npm-package-license.js) more [tests](https://github.com/jslicense/spdx-correct.js/blob/master/test.js), it is probably a good idea to test those with spdx-parse@2.0.2 before publishing it (`npm link`?).

**Comment by motet-a** [comment]
I have doubts about parentheses. I just opened #20.

**Comment by kemitchell** [comment]
I've just run the `spdx-correct` and `validate-npm-package-license` test suites with proposed 2.0.2. All tests pass.

**Comment by kemitchell** [comment]
@motet-a, would you like to register motet-a on npmjs.com? I will give you publish permissions on the package.

**Comment by motet-a** [comment]
@kemitchell [Done, I have just registered motet-a](https://www.npmjs.com/~motet-a). 

~~I used to have [https://www.npmjs.com/~motet_a](motet_a), but how stupid can I be to mix up dashes and underscores…~~

**Comment by kemitchell** [comment]
I've added you as a "contributor". You can publish with `npm publish`.

I'll continue to open pull requests for significant releases going forward. Do what you think best. If you have questions, don't be afraid to ask, publicly or privately.

**Pull request closed without merging**
