### PR TITLE
[WIP] Configure Travis CI to test with and without --use_strict

### PR DESCRIPTION
**Pull request by motet-a**
It works in strict mode now since #15.

### CODE REVIEW

**Comment by kemitchell** [comment]
@motet-a, this is good to know, I suppose. But unless something very basic has changed about `--use_strict` since it came up in #9, I wouldn't test for it, and I certainly wouldn't tell users to expect they can use it.

In a nutshell, `--use_strict` forces strict mode on all code, even code without the `'use strict'`. Imposing the semantics of strict mode like that isn't part of the spec, and breaks all kinds of packages.  I wish they'd never added that flag, and I'm not alone.

Unrelated: Did you do something strange with your Git configuration? I'm listed as `Author` on your commit for some reason!

**Comment by motet-a** [comment]
@kemitchell You are the author, this is an old commit from an old branch :-)

**Comment by kemitchell** [comment]
Ah, probably the branch I used to replicate #9.

**Comment by motet-a** [comment]
I don't see any problem with testing with and without `--use_strict` in the CI. This does not enforce strict mode anywhere and does not tell users they can use it. This only asserts that `spdx-expression-parse` works with and without strict mode.

In my humble opinion, since little effort is needed to support strict mode, since it is easy to write code that works with and without it and since it spots many pitfails, this is a good thing.

**Comment by kemitchell** [comment]
Strict mode and vanilla ES5 have intentionally different semantics.  But it isn't like two dialects of C: Both regular and strict-mode ES5 are specified in the same standard. It's completely up to the coder which dialect applies to which code, based on `'use strict'`. Or at least it was until Node exposed `--use_strict`, and a few people started using it.

If you really want strict mode, add `'use strict'` throughout the package, and make sure all the runtimes interpret it to run all the package code in strict mode.  Node back to 0.10 mostly does support it, though there are lots of subtle questions and bugs, related to the module system.

As a module author, `--use_strict` has been nothing but trouble.  I don't want to encourage it.  It has caused so many issues and pull requests.  Often because users didn't understand `--use_strict`, or the difference between strict mode and regular ECMAScript.

**Comment by motet-a** [comment]
OK, I will create another PR with `'use strict'` directives, it is definitely better. I totally agree that `--strict_mode` must not be used in production, I just thought it was a good way to assert that everything works in strict mode.

**Pull request closed without merging**
